### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by EXJUSTICE** [Gnzlt/AndroidVisionQRReader#2]
Could you give more details as to the integration?

Do I first copy the zip file down, or somehow create an AAR file?
I am at a loss as to where to start? :)

**Comment by iaubain** [comment]
You have to download the AndroidVisionQRReader application and in you IDE (in my case is android studio 2.2.3) I went to App>New>Module>Import Gradle Project and selected the downloaded "AndroidVisionQRReader " 
and it is done. make sure to handle all alert as they are coming and continue with the usage. 
Happy coding!

**Comment by Gnzlt** [comment]
You can also use `JitPack`. Add this in your root build.gradle at the end of repositories:
```
allprojects {
  repositories {
    ...
    maven { url 'https://jitpack.io' }
  }
}
```
And add the dependency:
```
dependencies {
  compile 'com.github.Gnzlt:AndroidVisionQRReader:1.1'
}
```
